Complete redux store for bookstore project
coderacheal/book-store pull request #2
Opened 2023-03-09 18:56 UTC by coderacheal

- Created a directory that will contain all your Redux logic (/src/redux)
- Configured a Redux store (/src/redux/store.js)
- Defined a slice of state for books that:
- Includes an array of books (initial state: empty array)
- Includes a reducer that adds a book
- Includes a reducer that removes a book
- Define a slice of state for categories that:
- Includes an array of categories (initial state: empty array)
- Includes a reducer that check the status and always return "Under construction"

2023-03-09 19:12 UTC, huseyinbiyik commented
Hi @coderacheal 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

⚠️ Kindly make sure you have a Readme created with [Microverse Readme Template](https://github.com/microverseinc/readme-template/blob/master/README.md).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-09 20:12 UTC, Deepakdanger requested changes
Hi @coderacheal & @huseyinbiyik, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 20:12 UTC, Deepakdanger commented on src/redux/books/booksSlice.js
> +    },
- [ ] I am not seeing any actions here. Please add the code to add and remove the book.

2023-03-10 05:31 UTC, uwadonat approved these changes
## Hi @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- No linter errors ✔️
- Professional readme file ✔️
- Good project structure ✔️
![approval1](https://user-images.githubusercontent.com/65860678/224231633-569a8d6e-06fb-439e-a0e5-3405737320c1.gif)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-10 05:31 UTC, merged